### ISSUE TITLE
capture outputs to the console when an error occurs.

### ISSUE THREAD

**Issue by bsutton** [google/dart_cli_script#36]
Looking at the capture method for use in dcli raises an issue.

The dcli contract is that we never output to the cli unless the user requests it. For the methods that do output (e.g. String.run) we provide an alternate method that doesn't output to the cli (String.start).

As I understand it the capture method always outputs to the cli if an error occurs.

This makes the capture method unusable from dcli.

I need a method that allows me to always control where the output goes.

**Comment by nex3** [comment]
`cli_script` has a different philosophy—we try to mirror shell script behavior as much as possible, so we output to the CLI by default because that's what shell scripts do. That said, you should be able to route around this by accessing `Script.stdout` and `Script.stderr` when you create the capture--that will disable the automatic piping to the parent context.
